### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HarryXD2018** [CreamNuts/Pytorch-Temporal-Interpolation-Model#1]
Hi, thanks for your work! 👍 

When I try the code on CASME II dataset (a facial micro-expression dataset), I run into assert code in line 33. Does the assertion necessary? I haven't went though the paper but it looks fine if I comment it. 

Harry 😄

**Comment by HarryXD2018** [comment]
Hi, it returns black img, looks like the assertion is necessary. How is that possible?

**Comment by CreamNuts** [comment]
Assertion is necessary for checking linear independency between frames because original paper assumes that. But paper validate that assumption only 30 fps video. So, for using TIM on CASME II, I remove assertion.

And I don't understand it returns black img. What it means?

**Comment by HarryXD2018** [comment]
Thanks for your reply 😄 . 

What I mean is when I try to visualize any frame of the transformed video, they are totally black images, less similar to the originals. Here is my [colab link](https://colab.research.google.com/drive/1nMNT_T8emY-B82ChCF3pjFTaG0CpdL0X?usp=sharing).

**Comment by CreamNuts** [comment]
I can't access your colab link. Please show me your code. In my case, there is no black image even though there is no assertion.

**Comment by HarryXD2018** [comment]
Sorry that my colab doesn't work. I changed the access control, maybe you can access to it this time. I pasted my code below: 

~~~python
import torch
from tim import FixSequenceTIM
from PIL import Image
from torchvision import transforms


tim_transform = FixSequenceTIM(sequence_length=20)

to_tensor = transforms.ToTensor()
to_PIL = transforms.ToPILImage()

tensor_list = []
for i in range(1, 14):
  img = Image.open('{:05d}.jpg'.format(i))
  img = to_tensor(img)
  tensor_list.append(img)
video = torch.stack(tensor_list)

video = tim_transform(video)
~~~

**Comment by CreamNuts** [comment]
For using TIM, video length must be longer than `sequence_length`.

**Comment by HarryXD2018** [comment]
Changing `sequence_length` is not working. 😢

**Comment by CreamNuts** [comment]
I'm sorry. Video length must be shorter than `sequence_length`

**Comment by HarryXD2018** [comment]
I guess I just figured out why it is black. Hmm, looks like I messed up with the `dtype`s. I am going to close the issue now. 

Thanks a lot!

**Comment by CreamNuts** [comment]
> I'm sorry. Video length must be shorter than `sequence_length`

I was confused because I wrote the code for the past. Short or long video length is not related for using TIM. I'm sorry for wrong information.

 Thank you.
